name: CI Pipeline

on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Set up Node.js environment using nvm
        run: |
          export NVM_DIR="$HOME/.nvm"
          mkdir -p $NVM_DIR
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
          . $NVM_DIR/nvm.sh
          nvm install
          nvm use
          node -v
        shell: bash

      - name: Enable corepack
        run: corepack enable

      # TODO: For production, use published version,
      # so it'd get installed as an external dependency,
      # instead of going through the same pipeline as it could in its own repository,
      # when being published
      - name: MedusaJS - Install dependencies
        working-directory: packages/medusa
        run: yarn install --immutable

      - name: MedusaJS - Build
        working-directory: packages/medusa
        run: yarn build

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build the project
        run: yarn build
